//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITProjectResourceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public int Specialty { get; set; }
        public Nullable<int> ProjectsAssigned { get; set; }
        //public int ProjectsAssigned { get; set; }

        public virtual Category Category { get; set; }
        public virtual Project Project { get; set; }
    }
}
