//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITProjectResourceManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public int ID { get; set; }
        public int Value { get; set; }
        public int ProjectID_FK { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
